name: CI
on:
  push:
    branches: [ dev, ci-setup ]
  pull_request:
    branches: [ dev ]
  workflow_dispatch:
jobs:
  run-linter:
    name: Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: ESLint
        uses: wearerequired/lint-action@v1
        with:
          eslint: true
          prettier: true
#  run-test:

